export function getHeaders(): Map<string, string> {
    let headers = new Map<string, string>();
    headers.set('fullName', 'Назва');
    headers.set('place', 'Місце розташування');
    headers.set('fullAddress', 'Адреса');
    headers.set('institutionType', 'Тип закладу');
    headers.set('totalPopulation', 'Населення, яке зареєстровано на території обслуговування закладу');
    headers.set('population', 'Населення, яке зареєстровано в населеному пункті');
    headers.set('subordinationLevel', 'Рівень підпорядкування');
    headers.set('placeType', 'Тип населеного пункту');
    headers.set('ownership', 'Форма власності');
    headers.set('legalFormCode', 'Код організаційно-правової форми');
    headers.set('receptionOffice', 'Приймальне відділення');
    headers.set('registryOffice', 'Реєстратура');
    headers.set('medicalCare', 'Рівень надання медичної допомоги');
    headers.set('medicalAidTypes', 'Види меддопомоги');
    headers.set('legalStatus', 'Статус юридичної особи');
    headers.set('license', 'Наявність ліцензії');
    headers.set('licenseNumber', 'Номер ліцензії');
    headers.set('accreditationCategoryType', 'Акредитаційна категорія');
    headers.set('accreditationCategoryNumber', 'Номер акредитаційної категорії');
    headers.set('typicalBuilding', 'Типовий проект');
    headers.set('heatingType', 'Опалення');
    headers.set('coldWaterSupply', 'Наявність холодного водопостачання');    
    headers.set('hotWaterSupply', 'Наявність гарячого водопостачання');
    headers.set('equipment', 'Оснащеність медичним обаднанням, %');
    headers.set('medicamentEquipment', 'Забезпеченість медикаментами, %');
    headers.set('internetSupply', 'Наявність доступу до мережі Інтернет');
    headers.set('stateRegisterCode', 'Код ЄДРПОУ');
    headers.set('phone', 'Контактний телефон');
    headers.set('headDoctorName', 'ПІП головного лікаря');
    headers.set('regularDoctorNumber', 'Лікарі (штатні)');
    headers.set('busyDoctorNumber', 'Лікарі (зайняті)');
    headers.set('individualsDoctorNumber', 'Лікарі (фізичні особи)');
    headers.set('middleRegularPersonalNumber', 'Середній медперсонал (штатні)');
    headers.set('middleBusyPersonalNumber', 'Середній медперсонал (зайняті)');
    headers.set('middleIndividualsPersonalNumber', 'Середній медперсонал (фізичні особи)');
    headers.set('otherRegularPersonalNumber', 'Інший персонал (штатні)');
    headers.set('otherBusyPersonalNumber', 'Інший персонал (зайняті)');
    headers.set('otherIndividualsPersonalNumber', 'Інший персонал (фізичні особи)');
    headers.set('totalRegularPersonalNumber', 'Всього (штатні)');
    headers.set('totalBusyPersonalNumber', 'Всього (зайняті)');
    headers.set('totalIndividualsPersonalNumber', 'Всього (фізичні особи)');
    headers.set('vehiclesNeed', 'Транспорті засоби (потреба)');
    headers.set('vehiclesReality', 'Транспорті засоби (наявність)');
    headers.set('vehiclesWay', 'Транспорті засоби (на ходу)');
    headers.set('computerEquipmentNeed', 'Комп\'ютерна техніка (потреба)');
    headers.set('computerEquipmentReality', 'Комп\'ютерна техніка (наявність)');
    headers.set('hospitalBedsNumber', 'Кількість ліжок стаціонару');
    headers.set('hospitalCapacity', 'Планова ємність амбулаторно-поліклінічного підрозділу');
    headers.set('technicalCondition', 'Технічний стан забудови станом на 31.12');
    headers.set('totalHospitalArea', 'Загальна площа стаціонару');
    headers.set('totalAmbulanceArea', 'Загальна площа амбулаторії');
    return headers;
}
