import { Injectable } from '@angular/core';
import { Institution } from '../models/institution';
import * as Excel from 'exceljs/dist/exceljs.min';
import { saveAs } from 'file-saver';
import { Observable, of } from '../../../node_modules/rxjs';
import { map } from '../../../node_modules/rxjs/operators';

@Injectable()
export class ExcelService {

  constructor() { }

  public getExcelFromInstitution(institution: Institution) {
    const workbook = new Excel.Workbook();
    let worksheet = workbook.addWorksheet(institution.fullName);
    worksheet.mergeCells('A1:B1');
    worksheet.getCell('A1').value = institution.fullName;
    worksheet.getColumn(1).width = 55;
    worksheet.getColumn(2).width = 55;
    worksheet.getColumn(1).alignment = { vertical: 'center', wrapText: true }
    worksheet.getColumn(2).alignment = { vertical: 'center',horizontal: 'left', wrapText: true }
    worksheet.addRow(['Місце розташування']);
    worksheet.getCell('B2').value = institution.place;
    worksheet.addRow(['Рівень підпорядкування']);
    worksheet.getCell('B3').value = institution.subordinationLevel;
    worksheet.addRow(['Тип населеного пункту місця розташування']);
    worksheet.getCell('B4').value = institution.placeType;
    worksheet.addRow(['Адреса']);
    worksheet.getCell('B5').value = institution.fullAddress;
    worksheet.addRow(['Кількість населення, яке офіційно зареєстровано на території обслуговування закладу (постійне на 01.01)']);
    worksheet.getCell('B6').value = institution.totalPopulation;
    worksheet.addRow(['Кількість населення, яке офіційно зареєстровано в населеному пункті']);
    worksheet.getCell('B7').value = institution.population;
    worksheet.addRow(['Email установи']);
    worksheet.getCell('B8').value = institution.email;
    worksheet.addRow(['Контактний телефон закладу']);
    worksheet.getCell('B9').value = institution.phone;
    worksheet.addRow(['Факс']);
    worksheet.getCell('B10').value = institution.fax;
    worksheet.addRow(['Сайт в Internet']);
    worksheet.getCell('B11').value = institution.site;
    worksheet.addRow(['Статус юридичної особи']);
    worksheet.getCell('B12').value = institution.legalStatus;
    worksheet.addRow(['Код ЄДРПОУ']);
    worksheet.getCell('B13').value = institution.stateRegisterCode;
    worksheet.addRow(['Код КОАТУУ']);
    worksheet.getCell('B14').value = institution.classifierObjectCode;
    worksheet.addRow(['Форма власності']);
    worksheet.getCell('B15').value = institution.ownership;
    worksheet.addRow(['Код організаційно-правової форми (КОПФ)']);
    worksheet.getCell('B16').value = institution.legalFormCode;
    worksheet.addRow(['ПІП головного лікаря (заступника)']);
    worksheet.getCell('B17').value = institution.headDoctorName;
    worksheet.addRow(['Робочий телефон']);
    worksheet.getCell('B18').value = institution.headDoctorWorkPhone;
    worksheet.addRow(['Мобільний телефон']);
    worksheet.getCell('B19').value = institution.headDoctorMobile;
    worksheet.addRow(['ПІП секретаря головного лікаря']);
    worksheet.getCell('B20').value = institution.secretaryHeadDoctorName;
    worksheet.addRow(['Робочий телефон']);
    worksheet.getCell('B21').value = institution.secretaryHeadDoctorPhone;
    worksheet.addRow(['Приймальне відділення']);
    worksheet.getCell('B22').value = institution.receptionOffice;
    worksheet.addRow(['Телефон']);
    worksheet.getCell('B23').value = institution.receptionOfficePhone;
    worksheet.addRow(['Реєстратура амбулаторно-поліклінічного підрозділу']);
    worksheet.getCell('B24').value = institution.registryOffice;
    worksheet.addRow(['Телефон']);
    worksheet.getCell('B25').value = institution.registryOfficePhone;
    worksheet.addRow(['Рівень надання медичної допомоги']);
    worksheet.getCell('B26').value = institution.medicalCare;
    worksheet.addRow(['Планова ємність']);
    worksheet.addRow(['Кількість ліжок стаціонару']);
    worksheet.getCell('B28').value = institution.hospitalBedsNumber;
    worksheet.addRow(['Планова ємність амбулаторно-поліклінічного підрозділу']);
    worksheet.getCell('B29').value = institution.hospitalCapacity;
    worksheet.addRow(['Тип закладу']);
    worksheet.getCell('B30').value = institution.institutionType;
    worksheet.addRow(['Види меддопомоги, які надає ЗОЗ']);
    worksheet.getCell('B16').value = institution.medicalAidTypes;
    worksheet.addRow(['Наявність ліцензії']);
    worksheet.getCell('B32').value = institution.license;
    worksheet.addRow(['№']);
    worksheet.getCell('B33').value = institution.licenseNumber;
    worksheet.addRow(['Дата']);
    worksheet.getCell('B34').value = institution.licenseDate;
    worksheet.addRow(['Термін дії з']);
    worksheet.getCell('B35').value = institution.startLicenseValidity;
    worksheet.addRow(['по']);
    worksheet.getCell('B36').value = institution.endLicenseValidity;
    worksheet.addRow(['Задекларовані види допомоги']);
    worksheet.getCell('B37').value = institution.declaredAssistanceForms;
    worksheet.addRow(['Акредитаціна категорія']);
    worksheet.getCell('B38').value = institution.accreditationCategoryType;
    worksheet.addRow(['№']);
    worksheet.getCell('B39').value = institution.accreditationCategoryNumber;
    worksheet.addRow(['Дата останньої акредитації']);
    worksheet.getCell('B40').value = institution.lastAccreditation;
    worksheet.addRow(['Термін дії з']);
    worksheet.getCell('B41').value = institution.startAccreditationValidity;
    worksheet.addRow(['по']);
    worksheet.getCell('B42').value = institution.endAccreditationValidity;
    worksheet.addRow(['Ресурси закладу']);
    worksheet.addRow(['Всього посад']);
    worksheet.addRow(['Штатні']);
    worksheet.addRow(['Зайняті']);
    worksheet.addRow(['Фізичні особи']);
    worksheet.addRow(['Лікарі']);
    worksheet.addRow(['Штатні']);
    worksheet.getCell('B49').value = institution.regularDoctorNumber;
    worksheet.addRow(['Зайняті']);
    worksheet.getCell('B50').value = institution.busyDoctorNumber;
    worksheet.addRow(['Фізичні особи']);
    worksheet.getCell('B51').value = institution.individualsDoctorNumber;
    worksheet.addRow(['Середній м/п']);
    worksheet.addRow(['Штатні']);
    worksheet.getCell('B53').value = institution.middleRegularPersonalNumber;
    worksheet.addRow(['Зайняті']);
    worksheet.getCell('B54').value = institution.middleBusyPersonalNumber;
    worksheet.addRow(['Фізичні особи']);
    worksheet.getCell('B55').value = institution.middleIndividualsPersonalNumber;
    worksheet.addRow(['Інший персонал']);
    worksheet.addRow(['Штатні']);
    worksheet.getCell('B56').value = institution.otherRegularPersonalNumber;
    worksheet.addRow(['Зайняті']);
    worksheet.getCell('B58').value = institution.otherBusyPersonalNumber;
    worksheet.addRow(['Фізичні особи']);
    worksheet.getCell('B59').value = institution.otherBusyPersonalNumber;
    worksheet.addRow(['Характеристика забудови (типовий проект)']);
    worksheet.getCell('B60').value = institution.typicalBuilding;
    worksheet.addRow(['Опалення']);
    worksheet.getCell('B61').value = institution.heatingType;
    worksheet.addRow(['Наявність централізованого холодного водопостачання']);
    worksheet.getCell('B62').value = institution.coldWaterSupply;
    worksheet.addRow(['Наявність гарячого водопостачання']);
    worksheet.getCell('B63').value = institution.hotWaterSupply;
    worksheet.addRow(['Оснащеність медичним обладнанням та інвентарем']);
    worksheet.getCell('B64').value = institution.equipment;
    worksheet.addRow(['Забезпеченість медикаментами для надання невідкладної допомоги']);
    worksheet.getCell('B65').value = institution.medicamentEquipment;
    worksheet.addRow(['Транспортні засоби']);
    worksheet.addRow(['Потреба (кількість)']);
    worksheet.getCell('B67').value = institution.vehiclesNeed;
    worksheet.addRow(['Наявність (кількість)']);
    worksheet.getCell('B68').value = institution.vehiclesReality;
    worksheet.addRow(['В т.ч. на ходу']);
    worksheet.getCell('B69').value = institution.vehiclesWay;
    worksheet.addRow(['Наявність доступу до мережі Internet']);
    worksheet.getCell('B70').value = institution.internetSupply;
    worksheet.addRow(['Забезпеченість ЗОЗ комп. технікою']);
    worksheet.addRow(['Потреба (кількість)']);
    worksheet.getCell('B72').value = institution.computerEquipmentNeed;
    worksheet.addRow(['Наявність (кількість)']);
    worksheet.getCell('B73').value = institution.computerEquipmentReality;
    worksheet.getCell('A1').alignment = { vertical: 'center', horizontal: 'center' };
    workbook.xlsx.writeBuffer().then(data => {
      saveAs(new Blob([data], { type: "application/octet-stream" }), institution.fullName + '.xlsx')
    })
  }
}
